use std::env;
use std::fs;
use std::path::Path;

fn make_aumid_rs()
{
	let metadata = cargo_metadata::MetadataCommand::new()
		.no_deps()
		.exec()
		.expect("Failed to read Cargo.toml metadata");

	let aumid = metadata
		.root_package()
		.and_then(|pkg| pkg.metadata.get("aumid").and_then(|v| v.as_str()))
		.expect("aumid not found in Cargo.toml");

	let out_dir = env::var("OUT_DIR").unwrap();
	let dest_path = format!("{}/aumid.rs", out_dir);
	fs::write(dest_path, format!("pub const AUMID : &str = \"{}\";", aumid))
		.expect("Failed to write AUMID file");
}

fn make_license_rs()
{
    let top_dir = env::var("TOP_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let license_path = Path::new(&top_dir).join("License.html");

    let license = fs::read_to_string(license_path)
        .expect("Failed to read License.html");

    let mut contents = String::new();
    contents.push_str("/// This file is automatically generated by build.rs\n");
    contents.push_str("pub const LICENSE_HTML: &str = r###\"");
    contents.push_str(&license);
    contents.push_str("\"###;\n");

    let dest_path = Path::new(&out_dir).join("license.rs");
    fs::write(&dest_path, contents).expect("Failed to write license.rs");
}

fn main() {
	make_aumid_rs();
    make_license_rs();
    tauri_build::build()
}
