[package]
name = "oops_time"
version = "0.1.0"
edition = "2021"
authors = ["KATOI <katoi4423@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
windows = {version = "*",features = [
	"Win32_System_LibraryLoader",
	"Win32_System_Threading",
	"Win32_UI_WindowsAndMessaging",
]}
